[theme]
primaryColor = "#FD8624"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "debug"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

# Use a line like this for development on a Cloud Workstation:
serverAddress = "https://8501-w-mcontri.cluster-6qq3ruvde5e36vzdfmpgxa2hxs.cloudworkstations.dev/"
